services:
  jupyter:
    image: jusher/jupyterlab-minimalist:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]